export const START_SCROLLER = "START_SCROLLER";
export const END_SCROLLER = "END_SCROLLER";

export const START_HOMEPAGE_SCROLLER = "START_HOMEPAGE_SCROLLER";
export const END_HOMEPAGE_SCROLLER = "END_HOMEPAGE_SCROLLER";

export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const HIDE_BACKDROP = "HIDE_BACKDROP";

export const START_MOVIE_SELECTION = "START_MOVIE_SELECTION";

export const START_SEARCH_TEXT = "START_SEARCH_TEXT";

export const SHOW_SEARCH_FIELD = "SHOW_SEARCH_FIELD";
export const HIDE_SEARCH_FIELD = "HIDE_SEARCH_FIELD";
